export enum Subject {
  All = 'all',

  Article = 'article',
  Billing = 'billing',
  Block = 'block',
  Template = 'template',
  Feed = 'feed',
  FeedRun = 'feedRun',
  Folder = 'folder',
  Gpt = 'gpt',
  GptRequest = 'gptRequest',
  Organization = 'organization',
  Role = 'role',
  Tag = 'tag',
  User = 'user',
  UserRole = 'userRole',
  UserNotification = 'userNotification',
  ContactsProvider = 'contactsProvider',
  EmailsProvider = 'emailsProvider',
}
