export enum Subject {
  User = 'user',
  Organization = 'organization',
  Role = 'role',
  UserRole = 'userRole',
  Feed = 'feed',
  FeedRun = 'feedRun',
  Article = 'article',
  Billing = 'billing',
  Tag = 'tag',
  Gpt = 'gpt',
  GptRequest = 'gptRequest',
  Block = 'block',
  Folder = 'folder',
}
