export enum StripeWebhookEventType {
  BILLING_PORTAL_CONFIGURATION_CREATED = 'billing_portal.configuration.created',
  BILLING_PORTAL_CONFIGURATION_UPDATED = 'billing_portal.configuration.updated',
  BILLING_PORTAL_SESSION_CREATED = 'billing_portal.session.created',
  CHECKOUT_SESSION_COMPLETED = 'checkout.session.completed',
  CUSTOMER_CREATED = 'customer.created',
  CUSTOMER_UPDATED = 'customer.updated',
  CUSTOMER_SUBSCRIPTION_CREATED = 'customer.subscription.created',
  CUSTOMER_SUBSCRIPTION_UPDATED = 'customer.subscription.updated',
  PAYMENT_INTENT_CREATED = 'payment_intent.created',
  PAYMENT_INTENT_SUCCEEDED = 'payment_intent.succeeded',
  INVOICE_CREATED = 'invoice.created',
  INVOICE_INCOMING = 'invoice.incoming',
  INVOICE_UPCOMING = 'invoice.upcoming',
  INVOICE_UPDATED = 'invoice.updated',
  INVOICE_FINALIZED = 'invoice.finalized',
  INVOICE_PAID = 'invoice.paid',
  INVOICE_PAYMENT_SUCCEEDED = 'invoice.payment_succeeded',
}
