name: Build, lint, test and push

on:
  push:
    branches:
      - main

jobs:
  package:
    env:
      WEBHOOK_ENDPOINT: https://example.org/webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v1
        with:
          node-version: '20.9.0'

      - name: Echo environment variable
        run: echo $WEBHOOK_ENDPOINT

      - name: Install dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm run lint

      - name: Run tests with Jest
        run: npm run test

      - name: Compile Typescript
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: backend
          path: |
            dist
            node_modules

  docker:
    needs: package
    runs-on: ubuntu-latest
    steps:

      # This will check out only the Dockerfile
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false

      # Must be after checkout to not be erased by it
      - uses: actions/download-artifact@v4
        with:
          name: backend
          path: .

      - name: List available files
        run: |
          ls -l
          ls -l dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: wiresantoine/saas-factory:latest
